# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       libcreds3

# >> macros
# << macros

Summary:    Credentials retrieval library
Version:    1.3.1
Release:    1
Group:      System/Libraries
License:    BSD
URL:        http://meego.gitorious.org/meego-platform-security
Source0:    %{name}-%{version}.tar.gz
Source100:  libcreds3.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  libsmack-devel
Provides:   libcreds2 >= 1.3.0
Obsoletes:   libcreds2 < 1.3.0

%description
This library enables access to the credentials of an another process.


%package devel
Summary:    Development files for libcreds3
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Provides:   libcreds2-devel >= 1.3.0
Obsoletes:  libcreds2-devel < 1.3.0

%description devel
devel packages for %{name}

%package tools
Summary:    Tools for libcreds3
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}

%description tools
Utilities for %{name}

%prep
%setup -q -n %{name}-%{version}/%{name}

# >> setup
autoreconf -f -i -s
%configure --disable-static
# << setup

%build
# >> build pre
# << build pre


make

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/*.so.*
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/libcreds.so
%{_includedir}/sys/creds.h
# << files devel

%files tools
%defattr(-,root,root,-)
# >> files tools
%{_bindir}/creds-get
%{_bindir}/creds-test
# << files tools
